### ISSUE TITLE
Can't Level up characters

### ISSUE THREAD

**Issue by ClayGolemDM** [geoidesic/foundryvtt-actor-studio#101] opened 2024-09-23 08:31 UTC
Levelling up a character provides only a blank screen. 
<img width="779" alt="image" src="https://github.com/user-attachments/assets/0311d189-c39d-4930-987f-a97ca6aee0f7">

Creating a character works just fine. But no ability to level up

V12
D&D 3.3.1  (also tested in 4.0, same thing)
AS: 1.5.4

NOTE: Disable Level Automation is not ticked. Tried with Ticked, just in case, but same result.

**Comment by geoidesic** [comment] 2024-09-23 11:40
Duplicate of #100 fixed in v1.5.5

**Closed by geoidesic** 2024-09-23 11:40 UTC
